### ISSUE TITLE
Open with Python

### ISSUE THREAD

**Issue by robinfays12** [Buzz-Beater/Watch-n-Patch-Feature-Extraction#1]
Hey,

I would like to have the skeleton data on Python. Do you think it's possible from your code ?

Thanks :)

**Comment by Buzz-Beater** [comment]
Hi,

I think the skeleton data is provided with the original dataset download,
the purpose of this repo is to reproduce the kernel descriptor features and
the additional skeleton features (distance and angles). I think you can
transform the skeleton from body.mat inside each data directory to python
directly.

Best,
Baoxiong

**Comment by robinfays12** [comment]
Hey,

I still have a question. When I open it, I have a lot of data. Do you know which are the x, y and z (for instance in the picture (kitchen 01-05-11) , what are the 3 values) ?

![image](https://user-images.githubusercontent.com/56922763/94526858-6f13f300-0236-11eb-9dbf-fd0bed004655.png)


Thanks for your answer.

K.R.,

Robin
